### PR TITLE
Adds a new post method that allows a single label's XML to be sent to the printer

### PR DESCRIPTION
**Pull request by georgepstaylor**

### CODE REVIEW

**Comment by seven1m** [comment]
@georgepstaylor I'm curious your use-case here... I don't think the JavaScript library uses such an endpoint... is this for custom software or a custom library of some sort? How does the existing functionality not work for you?

**Comment by georgepstaylor** [comment]
In reality, I couldn't get the existing functionality to work... I figured out that you need to post labelXml and labelSetXml to the endpoint, but... I have no idea what I need to post? I created this so that I could literally send a single label's XML to the endpoint and it'd print. Maybe I'm missing something in regard to /DYMO/DLS/Printing/PrintLabel?

**Comment by seven1m** [comment]
The purpose of my little program is to provide the backend for the [JavaScript SDK that Dymo provides](http://developers.dymo.com/2018/05/29/updated-js-sdk-and-dls/). If you yourself are writing code that does the POST request, then that's not within the scope of what this is for. I hope that helps!

**Comment by georgepstaylor** [comment]
Oh no, the code in the pull request doesn’t perform a post request, it provides another endpoint. So when you run agent.rb you can then post to /DYMO/DLS/Printing/PrintSingleLabel/ with the parameter labelXml. The xml is rendered my dymo-renderer and then sent to the printer as normal. 

I created this because the endpoint /DYMO/DLS/Printing/PrintLabel/ seemed to be for printing label sets rather than a single label at a time - at least that’s what I gathered from the Dymo SDK documentation.

**Comment by seven1m** [comment]
@georgepstaylor I'm sorry, but I don't see this being an addition to the project I want to merge. Here's my reasoning:

* The code is basically a copy of the `post '/DYMO/DLS/Printing/PrintLabel'` code above it with very minor tweaks.
* One could use the existing endpoint to print a single label by simply wrapping the object in a `<LabelRecord>` element. A single label is a label set of one. Hope that makes sense.
* It sounds like you are writing code that generates the XML, whereas I don't expect most people to be doing that. The JavaScript library provided by Dymo is doing that for them, in which case, the XML is generated properly for one or more labels.

I hate to turn down a contribution, but in this case, I cannot see the benefit to having more code to maintain when the existing code seems to work already.

**Comment by georgepstaylor** [comment]
Ah, actually, now I see what you mean! I didn't realise that by printing a label set, you could just print a single label in the way you described.

Completely understand, thanks for you explanation

**Pull request closed without merging**
