### PR TITLE
More label sizes, QR code support, graphics printing mode, set media size via lpr, better macOS font support

### PR DESCRIPTION
**Pull request by bgentry**
Hi there, thanks for making this project! I started off just adding a couple new label sizes but continued adding a bunch of other stuff I needed. If you want, this could be broken up into multiple PRs, but I did my best to keep each commit self-contained and self-explanatory.

Main highlights:

* Two new label sizes: 30330 + 30334
* Add QR code support.
* Set the paper orientation when printing (based on what's in the `.label` file)
* Set the media size when printing
* If the label has any barcodes, print in high-dpi graphics mode (as the Dymo software does)
* Support multiple font directories and file types on macOS (more dirs could easily be added for other platforms, didn't research if there are other standard locations on linux).

The QR code support differs slightly from the Dymo software. The main difference is that their software appears to use a fixed size per QR module (dot) so that it doesn't actually fill the bounding box. My implementation simply maximizes the size of the QR code within the bounding box.

This implementation also doesn't give you any errors when you attempt to fit too much data into the given physical size of the QR code; you'll just get an unreadable printout. IMO having a consistent QR size on the label makes much more sense to me. If you want to put more data in there, just make the code large enough to always accommodate that. 

Also, the QR codes generated here may be slightly different due to different encoding defaults. I couldn't figure out the settings to make it look exactly the same dot-for-dot, but that shouldn't matter as the basics are correct and these codes work fine.

This doesn't support *all* macOS fonts, but it gets most of them.

The main commit I'm not sure about is 79825d0. It was helpful when testing to know that fonts weren't being loaded correctly. I don't know if the desired behavior for users would be to raise an error in this case or silently fall back to a default font.

I might add some more barcode types but wanted to get this progress upstreamed first.

Partially addresses #1.

Cheers :v:

### CODE REVIEW

**Comment by bgentry** [comment]
Oh, if you want an example `.label` w/ a QR code let me know and I'll add one.

**Comment by bgentry** [comment]
I also added support for Code 128 barcodes, and removed the text vertical alignment hack in 6d6deb9.

**Comment by bgentry** [comment]
FYI, I went ahead and extracted the rendering-specific code into a separate rubygem named `dymo_render`: https://github.com/bgentry/dymo_render

I thought it made sense to have this PDF rendering portion be separate from the HTTP server portion. I of course kept all the copyright info.

Let me know if you have any thoughts! Super happy you got this project started because I probably wouldn't have been able to make it work without a good foundation 😄

**Comment by seven1m** [comment]
Whoa! I totally missed this!!! 🤦‍♂️ Thanks for your work on it. I’ll review and merge shortly.

**Comment by bgentry** [comment]
@seven1m no worries! I did get a ton of stuff fixed in that separate gem of mine, so it may make sense to just make the HTTP server part dependent on the gem.

**Comment by seven1m** [comment]
That's great, love the gem! I would indeed like to rip out the rendering code and just use your gem.

**Comment by seven1m** [comment]
I merged this via the terminal since GitHub was being difficult this morning. I'll now work on ripping out the renderer and using your gem instead!

**Pull request closed without merging**
